[theme]
primaryColor="#FF6F3C"  # Keep orange buttons and highlights consistent
backgroundColor="#FAF9F6"  # Light warm background for a soft appearance
secondaryBackgroundColor="#FFFFFF"  # White for input fields, dropdowns, and upload boxes
textColor="#000000"  # Ensure all text is black
font="sans serif"
